---
# Disabling Selinux
- name: Disable SeLinux
  hosts: all
  become: true
  tasks:
    - name: Checking Selinux is installed
      shell: "getenforce"
      register: val_selinux
      ignore_errors: yes

    - name: Disabling selinux
      shell: "echo \"SELINUX=disabled\">/etc/selinux/config"
      when:
        val_selinux.failed == false

    - name: verifying selinux status
      shell: "getenforce"
      register: output_selinux

    - name: Print Selinux status
      ansible.builtin.debug:
        msg: selinux is {{ output_selinux.stdout }}

# Setting swappiness
    - name: Setting swappiness
      sysctl:
        name: vm.swappiness
        value: 1
        state: present
        reload: yes

    - name: Checking swappiness
      shell: "sysctl vm.swappiness | awk '{print $NF}'"
      register: swapval

    - name: Verifing swappiness
      ansible.builtin.debug:
        msg: swappiness is set to {{ swapval.stdout }}

# Disabling IPV6
    - name: Disabling IPV6
      sysctl:
        name: net.ipv6.conf.all.disable_ipv6
        value: 1
        state: present
        reload: yes

    - name: Checking IPv6
      shell: "cat /proc/sys/net/ipv6/conf/all/disable_ipv6"
      register: val_ipv6

    - name: Verifying IPV6
      ansible.builtin.debug:
        msg: "Ipv6 is Disabled"
      when:
        val_ipv6.stdout == "1"

# Installing NameServer caching daemon
    - name: Verifying nscd package
      shell: "nscd --version"
      register: val_nscd
      ignore_errors: yes

    - name: Installing NSCD
      yum:
        name: nscd
        state: present
      when:
        val_nscd.failed

    - name: Verifying nscd package
      shell: "nscd --version | head -1 | awk '{print $NF}'"
      register: output_nscd
      ignore_errors: yes

    - name: Starting nscd
      shell: "service nscd start"

    - name: Displying nscd version
      ansible.builtin.debug:
        msg: nscd version is {{ output_nscd.stdout  }}

# Installing Packages
    - name: Installing packages
      yum:
        name: "{{ packages  }}"
      vars:
        packages:
        - wget
        - nano
        - net-tools
        - lsof
        - krb5-workstation
        - openldap
