---
- name: Disable SELinux
  ansible.posix.selinux:
    state: disabled
  notify:
    - Print Selinux status
  
# Setting swappiness to 1
- name: Setting swappiness
  ansible.posix.sysctl:
    name: vm.swappiness
    value: 1
    state: present
    reload: yes
  
# Disabling IPV6
- name: Disabling IPV6
  ansible.posix.sysctl:
    name: net.ipv6.conf.all.disable_ipv6
    value: 1
    state: present
    reload: yes
  
# Installing NameServer caching daemon
- name: Installing NSCD
  yum:
    name: nscd
    state: present
    ignore_errors: true
  
# Disabling Transparent Huge Pages

- name: checking for THP
  shell: " echo \"if test -f /sys/kernel/mm/transparent_hugepage/enabled; then\n
  echo never > /sys/kernel/mm/transparent_hugepage/enabled \n
fi\n
if test -f /sys/kernel/mm/transparent_hugepage/defrag; then \n
  echo never > /sys/kernel/mm/transparent_hugepage/defrag \n
fi\n
\" >> /etc/rc.local"
      
# Installing tools
- name: Installing packages
  ansible.builtin.yum:
    name: "{{ tools  }}"
    state: present

# Removing Tuned package
    - name: Removing tuned
      ansible.builtin.dnf:
         name: tuned
         state: removed
         autoremove: yes
      
# Setting up TCP Selective acknowledgement conf
- name: Setting up TCP sack
      ansible.posix.sysctl:
        name: net.ipv4.tcp_sack
        value: 1
        state: present
        reload: true

# Setting up maximum length of processor input queues
    - name: Setting up maximum length of processor input queues
      ansible.posix.sysctl:
        name: net.core.netdev_max_backlog
        value: 250000
        state: present
        reload: true

