---
# handlers for Selinux task
- name: Print Selinux status
  ansible.builtin.debug:
    msg: Configuration is done please restart !!

# handlers for swappiness
- name: Checking swappiness
  shell: "sysctl vm.swappiness | awk '{print $NF}'"
  register: swapval

- name: Verifying swappiness
  ansible.builtin.debug:
    msg: swappiness is set to {{ swapval.stdout }}
 
# handlers for IPV6
- name: Checking IPV6
  shell: "cat /proc/sys/net/ipv6/conf/all/disable_ipv6"
  register: val_ipv6

- name: Verifying IPV6
  ansible.builtin.debug:
    msg: "Ipv6 is Disabled"
  when:
    val_ipv6.stdout == "1"

# handlers for nscd
- name: Verifying nscd package
  shell: "nscd --version | head -1 | awk '{print $NF}'"
  register: output_nscd
  ignore_errors: yes

- name: Starting nscd
  shell: "service nscd start"

- name: Displying nscd version
  ansible.builtin.debug:
    msg: nscd version is {{ output_nscd.stdout }}

# handlers for thp
- name: reloading rc.d
  shell: "source /etc/rc.local"

- name: verifying disbled thp
  shell: "cat /sys/kernel/mm/transparent_hugepage/enabled"
  register: val_thp

- name: Status of THP
  ansible.builtin.debug:
    msg: "{{ val_thp.stdout }}"

# Handlers for tuned
- name: status of tuned
  ansible.builtin.debug:
    msg: tuned package is removed
    
- name: reloading sysctl daemon
  shell: "systemctl daemon-reload"
